### ISSUE TITLE
Runtime error in "Introduction to Pyresample" notebook

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/gridding-cookbook#9]
It's visible here:
https://projectpythia.org/gridding-cookbook/notebooks/pyresample_intro.html#loading-in-one-netcdf

The line that triggers the error is
```
area_def, cf_info = load_cf_area('data/onestorm.nc', variable='visible', x='x', y='y')
```

I'm not sure why our CI testing is not flagging this as failing.

@ThomasMGeo any ideas about a code fix here?

**Comment by ThomasMGeo** [comment]
That section is supposed to fail! Check the comment right below it.

**Comment by brian-rose** [comment]
So it is! I should have spent the additional 10 seconds to see that, sorry!

The issue now is that the cell needs to be labeled with the `raises-exception` cell tag so that execution will continue after the expected failure.

I can open a PR for that.

**Comment by ThomasMGeo** [comment]
Thanks for doing all the work on this @brian-rose !

**Comment by brian-rose** [comment]
This is sorted out now after #12
